# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/wboyz/simplecatalog/models/category/fields.yaml

# Model Class name
modelClass: Wboyz\SimpleCatalog\Models\Category

# Default redirect location
defaultRedirect: wboyz/simplecatalog/categories

# Create page
create:
    title: Create Category
    redirect: wboyz/simplecatalog/categories/update/:id
    redirectClose: wboyz/simplecatalog/categories

# Update page
update:
    title: Edit Category
    redirect: wboyz/simplecatalog/categories
    redirectClose: wboyz/simplecatalog/categories

# Preview page
preview:
    title: Preview Category